controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

adminController:
    path: /admin
    controller: App\Controller\AdminController::index

blogController:
    path: /
    controller: App\Controller\BlogController::index

postController:
    path: /post/{post_id}
    controller: App\Controller\PostController::index

loginController:
    path: /admin/login
    controller: App\Controller\LoginController::index