controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin:
    path: /admin
    controller: App\Controller\AdminController::index
login:
    path: /admin/login
    controller: App\Controller\AdminController::login

blog:
    path: /
    controller: App\Controller\BlogController::index
post:
    path: /post/{post_id}
    controller: App\Controller\BlogController::show_post
