#index:
#    path: /
#    controller: App\Controller\DefaultController::index
id:
  path: /id/{id}
  controller: App\Controller\ZwrotIDController::id
pokazpost:
  path: /pokazpost/{id}
  controller: App\Controller\PokazpostController::id